# Generated by Django 3.1.6 on 2021-02-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_comment_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_posted',
        ),
    ]
