# Generated by Django 3.1.6 on 2021-02-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_comment_prosmotr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='prosmotr',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
