# Generated by Django 3.1.6 on 2021-02-28 12:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0015_auto_20210228_1532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dislikes',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('post', 'user')},
        ),
    ]
